= ansible-role-mediawiki
Jonas Pammer <opensource@jonaspammer.at>;
:toc: left
:toclevels: 2
:toc-placement!:
:source-highlighter: rouge

ifdef::env-github[]
// https://gist.github.com/dcode/0cfbf2699a1fe9b46ff04c41721dda74#admonitions
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]

https://galaxy.ansible.com/jonaspammer/mediawiki[image:https://img.shields.io/badge/available%20on%20ansible%20galaxy-jonaspammer.mediawiki-brightgreen[Version on Galaxy]]
// Very Relevant Status Badges
https://github.com/JonasPammer/ansible-role-mediawiki/actions/workflows/ci.yml[image:https://github.com/JonasPammer/ansible-role-mediawiki/actions/workflows/ci.yml/badge.svg[Testing CI]]


An Ansible role for

* downloading mediawiki into a specified directory,
* installing recommended system packages
* downloading additional extensions and skins through Git or Composer

This role does *not* install/configure an SQL-Server.

This role does *not* install/configure a Webserver.

This role does *not* generate a LocalSettings.php
(https://github.com/JonasPammer/ansible-role-mediawiki/issues/2[yet]).

This role does *not* execute any of Mediawiki's maintenance scripts
(like `update.php` which you'll want to run for most extensions to work)
https://github.com/JonasPammer/ansible-role-mediawiki/issues/3[yet].

This role *does* try to ensure permissions of Mediawiki's files.

toc::[]

[[meta]]
== 🔎 Metadata
Below you can find information on…

* the role's required Ansible version
* the role's supported platforms
* the role's https://docs.ansible.com/ansible/latest/user_guide/playbooks_reuse_roles.html#role-dependencies[role dependencies]

.link:meta/main.yml[]
[source,yaml]
----
include::meta/main.yml[]
----


[[requirements]]
== 📌 Requirements
// Any prerequisites that may not be covered by this role or Ansible itself should be mentioned here.
The Ansible User needs to be able to `become`.

The https://galaxy.ansible.com/community/general[`community.general` collection]
must be installed on the Ansible controller.

`composer` needs to be installed on the Host
in order for the extension downloading functionality to work
(even when only using roles sourced from git only).

`git` needs to be installed on the Host
in order for the extension downloading functionality to work.

`unzip` is recommended to be installed
in order for composer to correctly unzip downloaded packets.


[[variables]]
== 📜 Role Variables
// A description of the settable variables for this role should go here
// and any variables that can/should be set via parameters to the role.
// Any variables that are read from other roles and/or the global scope (ie. hostvars, group vars, etc.)
// should be mentioned here as well.

[source,yaml]
----
# php_version: "7.2"
----
*Required to be set by yourself.*
Used in the names of the installed PHP Packages.
Variable-Name comes from the `php-versions` role.

[NOTE]
Keep in mind that the php version satisfies
https://www.mediawiki.org/wiki/Compatibility[MediaWiki's Compatibility Matrix].

[TIP]
This variable name intentionally overlaps with
https://github.com/geerlingguy/ansible-role-php-versions[ansible-role-php-versions].
It's recommended to have it be set in your host_vars specification,
because if you accidentally install even just one php package using an alternating version specifier
*it can mess up your entire system* (PHP system packages are weird).

[WARNING]
Leaving this blank will result in the installation of the symlink-packages of the system.

[source,yaml]
----
mediawiki_version_major: 1
mediawiki_version_minor: 39
mediawiki_version_release: 0
----
Version of Mediawiki to download.
See https://releases.wikimedia.org/mediawiki/[releases.wikimedia.org] and
https://en.wikipedia.org/wiki/MediaWiki_version_history[Wikipedia: MediaWiki Version History].

[source,yaml]
----
mediawiki_destination: [default htdocs of distro]/mediawiki
----
Folder in which to extract the downloaded mediawiki archive into.
Must *not* end with an "/".

The default points to a directory named `mediawiki`
in the default httpd' directory of the distribution:

* default: `/var/www/html`
* Alpine: `/var/www/{{ httpd_servername | default(ansible_fqdn) }}`
* Suse: `/srv/www/htdocs`

[source,yaml]
----
mediawiki_destination_permissions: u=rwx,g=rx,o=rx
----
The permissions the resulting directory should have.

[source,yaml]
----
mediawiki_linux_username: ~
mediawiki_linux_group: ~
----
User and Group that should own the destination directory itself.

[NOTE]
You will need to ensure these are created *beforehand* (e.g. using `pre_tasks`) -
the machine's passwd configuration is no business to this role.

[source,yaml]
----
mediawiki_enable_webserver: true
----
Enable/Disable this role's `restart httpd` handler.


=== Downloading Extensions

[TIP]
This can be skipped by https://docs.ansible.com/ansible/latest/user_guide/playbooks_tags.html#selecting-or-skipping-tags-when-you-run-a-playbook[
skipping the tag] `mediawiki::extensions`.

[TIP]
======
By using this role in combination with this variable and its structure
you could have something like this in your LocalSettings.php Template:
[source,jinja2]
----
{% for category_identfier, extensions_array in mediawiki_extensions.items() %}
# {{ category_identfier }} extensions
{%  for extension in extensions_array %}
{%      if extension.load %}
wfLoadExtension("{{ extension.name }}");
{%      endif %}
{%  endfor %}
{% endfor %}
----
======

[source,yaml]
----
mediawiki_extensions:
  unsorted: []
----
A _dictionary of lists_ of Extensions to download.

The dictionary keys are to attach an _arbitrary_
"category" to each extension. How you name these "categories"
is to your business only.


Each entry of a list may have the following properties
(Consult the <<example_playbooks>>-Section for Examples):

name::
Name of the Extension as used when registering the extension in `LocalSettings.php`.

load::
Boolean.
Can be used in the Jinja2 Template to decide if the extension shall be loaded.
Does not have any effect in this role.

gather_type::
This variable defines how to gather the extension.
Possible values: "composer", "git".
Defaults to "git".
+
======
Extensions can be *gathered* for a given MediaWiki-Version
through various ways.
As of 2021, the most common/supported way is by…

* Downloading the extension from Git to the `/extensions`-directory
* Optionally running `composer install [--no-dev …]` in the cloned directory
to install its dependencies in _its_ directory (kind-of-like `npm install`).
+
[NOTE]
====
When you download an extension from https://www.mediawiki.org/wiki/Special:ExtensionDistributor[
MediaWiki's Extension distributor], this step has already been done beforehand.
====

A more recent initiative attempts to implement the *sole* use of Composer to gather Mediawiki's Extensions
(instead of just using it for gathering libraries),
for-example by issuing `composer require mediawiki/semantic-media-wiki` in Mediawiki's base directory.
This is still https://phabricator.wikimedia.org/T250406[an actively discussed RFC].

This method can only be done if the extension exists as a "Composer package" of-course.

[NOTE]
====
No-matter which version is used to gather the extension, you'll still need to issue `wfLoadExtension`
in your "LocalSettings.php"-file.
====
======

composer_name::
Name of the composer package of the Extension, for example as found on https://packagist.org/search/?type=mediawiki-extension[
packagist.org].
+
[NOTE]
=====
It's a good Idea to pass in this value even if you plan to use git as the gather-method,
assuming your Extensions https://www.mediawiki.org/wiki/Category:Extensions_supporting_Composer[
exists as a composer package]. By doing so, this role can make sure Mediawiki's Composer does not contain this Composer Package
(which could cause the weirdest conflicts).

Also, if you do this, I like to explicitly specify the `gather_type` to be "git" myself.
=====

composer_version::
https://getcomposer.org/doc/articles/versions.md#writing-version-constraints[Version Constraint]
for the Composer Package.


composer_install_pre_config_actions::
For each value in this list an appropiate `composer config ...` command will be executed
prelimentary to the `composer <install/require> ...` that follows it.

Each value in this list may either be a string (equals to `{arguments: "[insert string]"}`)
or the following data type:

======
arguments::
literal value passed to https://docs.ansible.com/ansible/latest/collections/community/general/composer_module.html#parameter-arguments[community.general.composer's `arguments`].
======

One reason for this variable was the following error message:

----
        composer/installers contains a Composer plugin which is blocked by your all
        ow-plugins config. You may add it to the list if you consider it safe.
        You can run "composer config --no-plugins allow-plugins.composer/installers
         [true|false]" to enable it (true) or disable it explicitly and suppress th
        is exception (false)
        See https://getcomposer.org/allow-plugins
----

__git_mwrepo_name__::
If your extensions is under https://www.mediawiki.org/wiki/Category:Extensions_in_Wikimedia_version_control[
Wikimedias' version control], but uses a different name for their Repository than provided in `name`,
you can use this to supply the name as used in the MediaWiki Repository.
Look at the default of `git_url` to understand this.
Defaults to `name`.

git_url::
URL to `.git` from the repository of the extension.
Defaults to `https://github.com/wikimedia/mediawiki-extensions-{{ git_mwrepo_name }}.git`.

git_version::
What version of the repository to check out. This can be the literal string HEAD, a branch name, a tag name.
Defaults to `REL{{ mediawiki_version_major }}_{{ mediawiki_version_minor }}` if not provided.

git_run_composer_install::
Boolean or "always".
Whether to run `composer install` in the directory of the Extension.
Defaults to value of `mediawiki_extensions_git_run_composer_install_default`.
* If set to "always", the command will be executed on every run.
* If set to a truthy boolean value, the command will be executed if the issued git module reports a change.

_system_package_dependencies_::
Package name(s) to install to the system using https://docs.ansible.com/ansible/latest/collections/ansible/builtin/package_module.html#parameter-name[
ansible.builtin.package].



[source,yaml]
----
mediawiki_extensions_git_run_composer_install_default: true
----
Overwrites the default value for `git_run_composer_install` of every extension.


=== Downloading Skins

[TIP]
This can be skipped by https://docs.ansible.com/ansible/latest/user_guide/playbooks_tags.html#selecting-or-skipping-tags-when-you-run-a-playbook[
skipping the tag] `mediawiki::skins`.

[TIP]
====
By using this role in combination with this variable and its structure
you could have something like this in your LocalSettings.php Template:
[source,jinja2]
----
{% for skin in mediawiki_skins %}
wfLoadSkin( '{{ skin.name }}' );
{% endfor %}
----
====


[source,yaml]
----
mediawiki_skins: []
----
A list of Skins to download.

Each entry of the list may have the following properties
(Consult the <<example_playbooks>>-Section for Examples):

name::
Official Name, as used when loading the skin.
If your extensions falls under https://www.mediawiki.org/wiki/Category:Extensions_in_Wikimedia_version_control[
Wikimedias' version control]
you will only need to supply this value.

git_url::
URL to `.git` from the repository of the extension.
Defaults to `https://github.com/wikimedia/mediawiki-extensions-{{ name }}.git` if not provided.

git_version::
What version of the repository to check out. This can be the literal string HEAD, a branch name, a tag name.
Defaults to `REL{{ mediawiki_version_major }}_{{ mediawiki_version_minor }}` if not provided.



[[public_vars]]
== 📜 Facts/Variables defined by this role

Each variable listed in this section
is dynamically defined when executing this role (and can only be overwritten using `ansible.builtin.set_facts`) _and_
is meant to be used not just internally.


[[tags]]
== 🏷️ Tags

// Checkout https://github.com/tribe29/ansible-collection-tribe29.checkmk/blob/main/roles/server/README.md#tags
// for an awesome example of grouping tasks using tags

Tasks are tagged with the following
https://docs.ansible.com/ansible/latest/user_guide/playbooks_tags.html#adding-tags-to-roles[tags]:

[cols="1,1"]
|===
|Tag | Purpose

| mediawiki::extensions
|
| mediawiki::skins
|
|===

You can use Ansible to skip tasks, or only run certain tasks by using these tags. By default, all tasks are run when no tags are specified.

[[dependencies]]
== 👫 Dependencies
// A list of other roles should go here,
// plus any details in regard to parameters that may need to be set for other roles,
// or variables that are used from other roles.

* https://github.com/geerlingguy/ansible-role-php[geerlingguy.php] (This role only installs packages not included in the defaults of linked role)
* https://github.com/geerlingguy/ansible-role-php-mysql[geerlingguy.php-mysql]


[[example_playbooks]]
== 📚 Example Playbook Usages
// Including examples of how to use this role in a playbook for common scenarios is always nice for users.

[NOTE]
====
This role is part of https://github.com/JonasPammer/ansible-roles[
many compatible purpose-specific roles of mine].

The machine needs to be prepared.
In CI, this is done in `molecule/resources/prepare.yml`
which sources its soft dependencies from `requirements.yml`:

.link:molecule/resources/prepare.yml[]
[source,yaml]
----
include::molecule/resources/prepare.yml[]
----

The following diagram is a compilation of the "soft dependencies" of this role
as well as the recursive tree of their soft dependencies.

image:https://raw.githubusercontent.com/JonasPammer/ansible-roles/master/graphs/dependencies_mediawiki.svg[
requirements.yml dependency graph of jonaspammer.mediawiki]
====

.Recommended Play
====
[source,yaml]
----
roles:
  - jonaspammer.mediawiki

vars:
  mediawiki_destination: "/opt/my_wiki"
  mediawiki_linux_username: "root"
  mediawiki_linux_group: "root"
----
====

.Downloading Extensions and Skins
====
[TIP]
======
If an extensions is under https://www.mediawiki.org/wiki/Category:Extensions_in_Wikimedia_version_control[
Wikimedias' version control], you will only need to supply the `name` property.
// Wikimedia's version control and how they managed to implement this a standard at scale
// still astonishes me till today. At least they recognized SVN is garbage for code (yeah, looking at you philipp).
======

[source,yaml]
----
roles:
  - jonaspammer.mediawiki

vars:
  mediawiki_extensions:
    special_page:
      - name: "ExtendedFilelist"
        git_mwrepo_name: "BlueSpiceExtendedFilelist"
        git_run_composer_install: true
        composer_install_pre_config_actions:
          - "--no-plugins allow-plugins.composer/installers true"

    editor:
      - name: "CodeEditor"
      - name: "CodeMirror"
      - name: "VisualEditor"
      - name: "WikiEditor"

    parser:
      - name: "BOFH"
        git_url: "https://github.com/tessus/mwExtensionBOFH"
        git_version: "1.8"

    semantic_mediawiki:
      - name: "SemanticMediaWiki"
        gather_type: composer
        composer_name: "mediawiki/semantic-media-wiki"
        composer_version: "~3.0"
        composer_install_pre_config_actions:
          - "--no-plugins allow-plugins.wikimedia/composer-merge-plugin true"

    variable:
      - name: "HitCounters"
        gather_type: git  # We get it from git...
        composer_name: "mediawiki/hit-counters"  # ...but make sure that, if it was previously installed through composer, this role removes it from Mediawiki's Composer packages

  mediawiki_skins:
    - name: "Timeless"
    - name: "Vector"
    - name: "MonoBook"
    - name: "MinervaNeue"
----
====


[[tested-distributions]]
== 🧪 Tested Distributions

A role may work on different *distributions*, like Red Hat Enterprise Linux (RHEL),
even though there is no test for this exact distribution.

// good reference for what to follow -- most starred and pinned project of geerlingguy:
// https://github.com/geerlingguy/ansible-role-docker/blob/master/.github/workflows/ci.yml
|===
| OS Family | Distribution | Distribution Release Date | Distribution End of Life | Accompanying Docker Image

// https://ubuntu.com/about/release-cycle
| Debian
| Ubuntu 20.04 LTS
| 2021-04
| 2025-04
| https://github.com/geerlingguy/docker-ubuntu2004-ansible/actions?query=workflow%3ABuild[image:https://github.com/geerlingguy/docker-ubuntu2004-ansible/workflows/Build/badge.svg?branch=master[CI]]

| Debian
| Ubuntu 22.04 LTS
| 2022-04
| 2027-04
| https://github.com/geerlingguy/docker-ubuntu2204-ansible/actions?query=workflow%3ABuild[image:https://github.com/geerlingguy/docker-ubuntu2204-ansible/workflows/Build/badge.svg?branch=master[CI]]

// https://wiki.debian.org/DebianReleases
// https://wiki.debian.org/LTS
| Debian
| Debian 11
| 2021-08
| 2024-06 (2026-06 LTS)
| https://github.com/geerlingguy/docker-debian11-ansible/actions?query=workflow%3ABuild[image:https://github.com/geerlingguy/docker-debian11-ansible/workflows/Build/badge.svg?branch=master[CI]]

| Debian
| Debian 12
| 2023-06
| 2026-06 (2028-06 LTS)
| https://github.com/geerlingguy/docker-debian12-ansible/actions?query=workflow%3ABuild[image:https://github.com/geerlingguy/docker-debian12-ansible/workflows/Build/badge.svg?branch=master[CI]]
|===


[[tested-ansible-versions]]
== 🧪 Tested Ansible versions

The tested ansible versions try to stay equivalent with the
https://github.com/ansible-collections/community.general#tested-with-ansible[
support pattern of Ansible's `community.general` collection].
As of writing this is:

* 2.13 (Ansible 6)
* 2.14 (Ansible 7)
* 2.15 (Ansible 8)
* 2.16 (Ansible 9)


[[development]]
== 📝 Development
// Badges about Conventions in this Project
https://conventionalcommits.org[image:https://img.shields.io/badge/Conventional%20Commits-1.0.0-yellow.svg[Conventional Commits]]
https://results.pre-commit.ci/latest/github/JonasPammer/ansible-role-mediawiki/master[image:https://results.pre-commit.ci/badge/github/JonasPammer/ansible-role-mediawiki/master.svg[pre-commit.ci status]]
// image:https://img.shields.io/badge/pre--commit-enabled-brightgreen?logo=pre-commit&logoColor=white[pre-commit, link=https://github.com/pre-commit/pre-commit]

include::DEVELOPMENT.adoc[]


[[contributing]]
== 💪 Contributing
image:https://img.shields.io/badge/PRs-welcome-brightgreen.svg?style=flat-square[PRs Welcome]
https://open.vscode.dev/JonasPammer/ansible-role-mediawiki[image:https://img.shields.io/static/v1?logo=visualstudiocode&label=&message=Open%20in%20Visual%20Studio%20Code&labelColor=2c2c32&color=007acc&logoColor=007acc[Open in Visual Studio Code]]

include::CONTRIBUTING.adoc[]


[[changelog]]
== 🗒 Changelog
Please refer to the
https://github.com/JonasPammer/ansible-role-mediawiki/releases[Release Page of this Repository]
for a human changelog of the corresponding
https://github.com/JonasPammer/ansible-role-mediawiki/tags[Tags (Versions) of this Project].

Note that this Project adheres to Semantic Versioning.
Please report any accidental breaking changes of a minor version update.


[[license]]
== ⚖️ License

.link:LICENSE[]
----
include::LICENSE[]
----
