---
roles:
  - name: jonaspammer.bootstrap
  - name: geerlingguy.repo-remi
  - name: geerlingguy.php
  - name: geerlingguy.php-versions
  - name: geerlingguy.php-mysql
  - name: geerlingguy.git

# NOTE: list all collections used here (even if included in `ansible`)
collections:
  - name: community.general
