---
- name: prepare
  hosts: all
  become: true
  gather_facts: false

  vars:
    # https://www.mediawiki.org/wiki/Compatibility
    # https://www.php.net/supported-versions.php
    php_version: "7.4"

  roles:
    - role: jonaspammer.bootstrap
    - role: geerlingguy.repo-epel
      when: ansible_os_family == "RedHat"
    - role: geerlingguy.repo-remi
      when: ansible_os_family == "RedHat"
    - name: geerlingguy.php-versions
    - name: geerlingguy.php
    - name: geerlingguy.php-mysql
    - name: geerlingguy.git
    #    - name: jonaspammer.core_dependencies
