---
- name: prepare
  hosts: all
  become: true
  gather_facts: false

  roles:
    - name: jonaspammer.bootstrap
    - name: geerlingguy.php
    - name: geerlingguy.php-mysql
    - name: geerlingguy.git
    #    - role: jonaspammer.core_dependencies
