---
dependency:
  name: galaxy
  options:
    role-file: requirements.yml
    requirements-file: requirements.yml
lint: |
  set -e
  ansible-lint
driver:
  name: docker
platforms:
  # service-enabled Docker image by geerlingguy
  - name: instance-${TOX_ENVNAME}-${MOLECULE_DISTRO:-debian12}
    image: "geerlingguy/docker-${MOLECULE_DISTRO:-debian12}-ansible:latest"
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    cgroupns_mode: host
    privileged: true
    pre_build_image: true
provisioner:
  name: ansible
  playbooks:
    converge: ${MOLECULE_PLAYBOOK:-converge.yml}
    # https://molecule.readthedocs.io/en/latest/examples.html#sharing-across-scenarios
    prepare: ../resources/prepare.yml
  options:
    v: true
  config_options:
    defaults:
      interpreter_python: auto_silent
      callbacks_enabled: profile_tasks, timer, yaml
      stdout_callback: yaml
  inventory:
    host_vars:
      instance-ansible-4-fedora35:
        remi_repo_url: https://rpms.remirepo.net/fedora/remi-release-35.rpm
        remi_repo_gpg_key_url: https://rpms.remirepo.net/RPM-GPG-KEY-remi2021
      instance-ansible-5-fedora35:
        remi_repo_url: https://rpms.remirepo.net/fedora/remi-release-35.rpm
        remi_repo_gpg_key_url: https://rpms.remirepo.net/RPM-GPG-KEY-remi2021

verifier:
  name: ansible
